apiVersion: v1
kind: Service
metadata:
  labels:
    name: mysql
  name: mysql
spec:
  externalIPs:
    - 51.15.249.88
  ports:
    - protocol: TCP
      port: 3306
      selector:
        name: mysql
